### ISSUE TITLE
htmlparser throws on link tags without rel

### ISSUE THREAD

**Issue by klaemo** [hueniverse/metaphor#29]
Hey there!
I'm trying to parse a German newspaper website which apparently contains a `link` tag without a `rel` property.
```html
<link itemprop="primaryImageOfPage" href="http://img.zeit.de/politik/ausland/2016-06/cameron-farage-tv-debatte/wide__1300x731">
```

This makes the htmlparser throw:
```js
const Metaphor = require('metaphor')
const parser = new Metaphor.Engine({ preview: false })

parser.describe('http://www.zeit.de/politik/ausland/2016-06/brexit-tv-duell-david-cameron-nigel-farage-eu-austritt', (descr) => console.log(descr))

TypeError: Cannot read property 'split' of undefined
    at Object.HtmlParser2.Parser.onopentag (/Users/clemens/share-page/node_modules/metaphor/lib/tags.js:91:44)
    at Parser.onopentagend (/Users/clemens/share-page/node_modules/htmlparser2/lib/Parser.js:169:37)
    at Tokenizer._stateBeforeAttributeName (/Users/clemens/share-page/node_modules/htmlparser2/lib/Tokenizer.js:230:13)
    at Tokenizer._parse (/Users/clemens/share-page/node_modules/htmlparser2/lib/Tokenizer.js:658:9)
    at Tokenizer.write (/Users/clemens/share-page/node_modules/htmlparser2/lib/Tokenizer.js:632:7)
    at Parser.write (/Users/clemens/share-page/node_modules/htmlparser2/lib/Parser.js:331:18)
    at Object.exports.parse (/Users/clemens/share-page/node_modules/metaphor/lib/tags.js:142:12)
    at Object.exports.parse (/Users/clemens/share-page/node_modules/metaphor/lib/index.js:209:10)
    at Wreck.read (/Users/clemens/share-page/node_modules/metaphor/lib/index.js:148:36)
    at finish (/Users/clemens/share-page/node_modules/wreck/lib/index.js:328:20)
```

We should probably check for the existence of `rel` here https://github.com/hueniverse/metaphor/blob/master/lib/tags.js#L88

```js
if (name === 'link' && attributes.href && attributes.rel) {}
```

Thank you!

**Comment by klaemo** [comment]
Awesome! Thank you :+1:
