### ISSUE TITLE
Crash: Cannot read property 'tag' of undefined

### ISSUE THREAD

**Issue by robogeek** [hueniverse/metaphor#33]
For the most part this module works great.  I'm puzzled by the following crash.  I'm using the module in a static website generator, and the website I'm testing against has dozens of pages with links to YouTube video pages.  Since this doesn't report the URL triggering the problem, I'm not entirely sure which page is crashing.

It appears to be happening on one of the index pages -- each of these pages has about 60 youtube links to process, and to just get the thumbnail. 

Is this running past a usage limit?

```
/Users/david/ws/t/hmp/node_modules/metaphor/lib/ogp.js:119
                if (prev[sub] &&
                        ^

TypeError: Cannot read property 'tag' of undefined
    at Object.exports.describe (/Users/david/ws/t/hmp/node_modules/metaphor/lib/ogp.js:119:25)
    at /Users/david/ws/t/hmp/node_modules/metaphor/lib/index.js:216:33
    at Object.HtmlParser2.Parser.onend (/Users/david/ws/t/hmp/node_modules/metaphor/lib/tags.js:139:20)
    at Parser.onend (/Users/david/ws/t/hmp/node_modules/metaphor/node_modules/htmlparser2/lib/Parser.js:309:32)
    at Tokenizer._finish (/Users/david/ws/t/hmp/node_modules/metaphor/node_modules/htmlparser2/lib/Tokenizer.js:838:12)
    at Tokenizer.end (/Users/david/ws/t/hmp/node_modules/metaphor/node_modules/htmlparser2/lib/Tokenizer.js:829:25)
    at Parser.end (/Users/david/ws/t/hmp/node_modules/metaphor/node_modules/htmlparser2/lib/Parser.js:337:18)
    at Object.exports.parse (/Users/david/ws/t/hmp/node_modules/metaphor/lib/tags.js:144:12)
    at Object.exports.Engine.constructor.options._describe.setup.redirected.beforeRedirect.Wreck.request.exports.parse.Tags.parse [as parse] (/Users/david/ws/t/hmp/node_modules/metaphor/lib/index.js:212:10)
    at /Users/david/ws/t/hmp/node_modules/metaphor/lib/index.js:151:36
    at finish (/Users/david/ws/t/hmp/node_modules/metaphor/node_modules/wreck/lib/index.js:328:20)
    at wrapped (/Users/david/ws/t/hmp/node_modules/metaphor/node_modules/hoek/lib/index.js:871:20)
    at onReaderFinish (/Users/david/ws/t/hmp/node_modules/metaphor/node_modules/wreck/lib/index.js:399:16)
    at g (events.js:260:16)
    at emitNone (events.js:72:20)
    at emit (events.js:166:7)
```

**Comment by robogeek** [comment]
FYI - I put some caching into my code to try and not query for the same thing multiple times, but to remember previous query results.  No change in behavior -- still crashes.

**Comment by robogeek** [comment]
I tried this (check if prev is undefined) and the crash is avoided:

```
                const prev = (Array.isArray(properties[key]) ? properties[key][properties[key].length - 1] : properties[key]);
                if (prev && prev[sub] &&
                    sub !== 'secure_url') {

                    prev[sub] = [].concat(prev[sub]);
                    prev[sub].push(value);
                }
                else {
                    if (sub === 'secure_url') {
                        sub = 'url';
                    }

                    if (prev) prev[sub] = value;
                }
```
