### ISSUE TITLE
providers.json not in latest npm package v3.5.2

### ISSUE THREAD

**Issue by klaemo** [hueniverse/metaphor#40]
Hey Eran,
just noticed this:

```shell
ls -l node_modules/metaphor
total 40
-rwxr-xr-x  1 clemens  staff  1660 28 Jul 20:25 LICENSE
-rwxr-xr--  1 clemens  staff  8644 28 Jul 20:25 README.md
drwxr-xr-x  9 clemens  staff   306 29 Jul 12:48 lib
drwxr-xr-x  3 clemens  staff   102 29 Jul 12:48 node_modules
-rw-r--r--  1 clemens  staff  2636 29 Jul 12:48 package.json
```

which results in:

```
Error: Cannot find module '../providers.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/clemens/webapp-server/node_modules/metaphor/lib/index.js:13:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

in `v3.5.1` it was still there.

**Comment by hueniverse** [comment]
Ah! Need to fix .npmignore
